import { createStitches } from "@stitches/react";

export const {
  styled,
  css,
  globalCss,
  keyframes,
  theme,
  createTheme,
  getCssText,
} = createStitches({
  theme: {
    colors: {
      background: "",
      uiBackgroundDark: "",
      uiBackground: "",
      uiBackgroundLight: "",
      uiBorder: "",
      uiText: "",
      errorBackground: "",
      errorBorder: "",
      errorText: "",
      errorButtonBackground: "",
      errorButtonBackgroundHover: "",
      errorButtonBorder: "",
      errorButtonBorderHover: "",
      errorButtonText: "",
      errorButtonTextHover: "",
      infoBackground: "",
      infoBorder: "",
      infoText: "",
      infoButtonBackground: "",
      infoButtonBackgroundHover: "",
      infoButtonBorder: "",
      infoButtonBorderHover: "",
      infoButtonText: "",
      infoButtonTextHover: "",
      warningBackground: "",
      warningBorder: "",
      warningText: "",
      warningButtonBackground: "",
      warningButtonBackgroundHover: "",
      warningButtonBorder: "",
      warningButtonBorderHover: "",
      warningButtonText: "",
      warningButtonTextHover: "",
      successBackground: "",
      successBorder: "",
      successText: "",
      successButtonBackground: "",
      successButtonBackgroundHover: "",
      successButtonBorder: "",
      successButtonBorderHover: "",
      successButtonText: "",
      successButtonTextHover: "",
    },
  },
});

const darkTheme = createTheme({
  colors: {
    background: "",
    uiBackgroundDark: "",
    uiBackground: "",
    uiBackgroundLight: "",
    uiBorder: "",
    uiText: "",
    errorBackground: "",
    errorBorder: "",
    errorText: "",
    errorButtonBackground: "",
    errorButtonBackgroundHover: "",
    errorButtonBorder: "",
    errorButtonBorderHover: "",
    errorButtonText: "",
    errorButtonTextHover: "",
    infoBackground: "",
    infoBorder: "",
    infoText: "",
    infoButtonBackground: "",
    infoButtonBackgroundHover: "",
    infoButtonBorder: "",
    infoButtonBorderHover: "",
    infoButtonText: "",
    infoButtonTextHover: "",
    warningBackground: "",
    warningBorder: "",
    warningText: "",
    warningButtonBackground: "",
    warningButtonBackgroundHover: "",
    warningButtonBorder: "",
    warningButtonBorderHover: "",
    warningButtonText: "",
    warningButtonTextHover: "",
    successBackground: "",
    successBorder: "",
    successText: "",
    successButtonBackground: "",
    successButtonBackgroundHover: "",
    successButtonBorder: "",
    successButtonBorderHover: "",
    successButtonText: "",
    successButtonTextHover: "",
  },
});
